### ISSUE TITLE
Описание как работи backup системата и как се добавя нов проект в нея

### ISSUE THREAD

**Issue by mitio** [obshtestvo/backup-sys#1]
Две неща са много необходими за тази система:
## 1. Кратко описание как работи

Отговор на поне следните въпроси:
- Кой пуска периодично скриптовете (cron в контейнера, или отдалеченият бекъп сървър)?
- Ако е cron в контейнера, примерен ред за добавяне в crontab, или направо файл в `create-lxc` проекта, който да се копира в `cron.d`.
- Колко често се прави бекъп?
- Колко често се изсмуква бекъпа?
- Каква е процедурата при нужда за възстановяване на бекъп? От локални файлове, ако има такива - къде са - и ако няма - от файловете на отдалечената машина. Лице за контакт по тази точка, за отдалечената машина.
## 2. Кратко описание как да се подкара и настрои за нов проект/контейнер
- Трябва ли да се прави нещо изобщо? Ако можем, трябва да сведем това до минимум.
- Виждам, че MySQL и PostgreSQL бази данни се бекъпват автоматично, уж. Ако има нужда от настройки за това, нека се опише. Да е ясно какво друго се архивира по подразбиране.
- Къде се добавят директории, които да бъдат архивирани? Виждам, че май става директно в `/do_backup.sh`. Ако се променя този скрипт, май трябва да се добави и в това хранилище, в папка `cont` (защо е съкратена така, идея си нямам :)). Каква е схемата за това?

И т.н.

Поводът за това е контейнерът на glasatni, който има скрипт, но май няма реално работещ бекъп. Най-опасно е да си мислим, че има бекъп, но той да не работи.

Пингвам хората, които имат отношение по въпроса: @krokodilerian @tochev @tsikov

**Comment by krokodilerian** [comment]
mea culpa, ей-сега ще се хвана да видя какво съм имал впредвид като съм го писал.

**Comment by krokodilerian** [comment]
@mitio , проблемът с glasatni беше бъг в скрипта, оправил съм го в 0f021911526e08a3bc272008ac1f9fd98da3ce06, за останалото написах документация. Трябва да измисля как да ви дам достъп и да се сетя дали на някой от вас дадох ключовете, кажете кой ги има, кой ги иска и т.н., и дали има да се допише още нещо.

**Comment by tochev** [comment]
Сега си погледнах логовете - ключа го има в ~/.gnupg с passphrase - имам я на mail-a криптирана с моя ключ и би следвало да имам backup от ключа (но ще проверя дали действително го имам утре).

**Comment by mitio** [comment]
Васил е описал нещата.

Аз сложих и [един warning в backup файловете](https://github.com/obshtestvo/backup-sys/blob/master/host/do_backup.sh#L3-L15), за да може нечетящите хора да не пипат където не трябва.
