### ISSUE TITLE
Един authoritative източник на do_backup.sh

### ISSUE THREAD

**Issue by mitio** [obshtestvo/backup-sys#2]
В момента изглежда, че имаме две копия на generic версията на `do_backup.sh`:
1. `obshtestvo/backup-sys/host/do_backup.sh`
2. `obshtestvo/create-lxc/templates/do_backup.sh`

Мисля, че едно от двете трябва да отпадне. Или трябва да изтрием 1., или да променим `create-lxc` да ползва версията от `backup-sys` по някакъв начин. Повече ми харесва вторият вариант.

@tochev @krokodilerian мнения?

**Comment by tochev** [comment]
ох, аз си мсилех че съм отговорил на това - трябват и 2те:
1. `host/do_backup.sh` е това което се изпълнява на host-a (koi)
2. `template/do_backup.sh` е нещото което да се използва при нов container (т.е. е "sample")

**Comment by mitio** [comment]
Да, сега стоплих. Благодаря ти за разяснението!
